# Generated by Django 3.1.7 on 2021-03-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalhealth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_image',
        ),
    ]
