# Generated by Django 3.1.7 on 2021-03-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalhealth', '0003_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='image', upload_to='articles/'),
        ),
    ]
