# Generated by Django 3.1.7 on 2021-03-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalhealth', '0002_remove_article_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, upload_to='articles/'),
        ),
    ]
